package com.scriptles.cabinet.catalog.api;
import com.scriptles.cabinet.catalog.collection.CollectionType; import com.scriptles.cabinet.catalog.service.CatalogQueryService; import com.scriptles.cabinet.common.api.PageResponse; import com.scriptles.cabinet.media.translation.CatalogLocaleResolver; import com.scriptles.cabinet.media.translation.LocalizedResponse; import com.scriptles.cabinet.security.AuthenticatedUser; import lombok.RequiredArgsConstructor; import org.springframework.http.ResponseEntity; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.UUID;
@RestController @RequestMapping("/v1") @RequiredArgsConstructor public class CatalogController { private final CatalogQueryService service; private final CatalogLocaleResolver localeResolver;
 @GetMapping("/collections") public ResponseEntity<PageResponse<CollectionSummaryResponse>> collections(@RequestParam CollectionType type,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="50") int size,@RequestParam(defaultValue="POPULARITY") String sort,@RequestParam(required=false) String locale,@RequestHeader(name="Accept-Language",required=false) String acceptLanguage){String requested=localeResolver.resolve(locale,acceptLanguage).tag();return LocalizedResponse.ok(service.collections(type,page,size,sort,requested),requested,locale==null||locale.isBlank());}
 @GetMapping("/collections/{id}") public ResponseEntity<CollectionResponse> collection(@PathVariable UUID id,@AuthenticationPrincipal AuthenticatedUser user,@RequestParam(required=false) String locale,@RequestHeader(name="Accept-Language",required=false) String acceptLanguage){String requested=localeResolver.resolve(locale,acceptLanguage).tag();CollectionResponse response=service.collection(id,user==null?null:user.id(),requested);return LocalizedResponse.ok(response,response.resolvedLocale(),locale==null||locale.isBlank());}
 @GetMapping("/collections/slug/{slug}") public ResponseEntity<CollectionResponse> collectionSlug(@PathVariable String slug,@AuthenticationPrincipal AuthenticatedUser user,@RequestParam(required=false) String locale,@RequestHeader(name="Accept-Language",required=false) String acceptLanguage){String requested=localeResolver.resolve(locale,acceptLanguage).tag();CollectionResponse response=service.collectionBySlug(slug,user==null?null:user.id(),requested);return LocalizedResponse.ok(response,response.resolvedLocale(),locale==null||locale.isBlank());}
 @GetMapping("/franchises/{id}") public FranchiseResponse franchise(@PathVariable UUID id,@AuthenticationPrincipal AuthenticatedUser user){return service.franchise(id,user==null?null:user.id());}
 @GetMapping("/franchises/slug/{slug}") public FranchiseResponse franchiseSlug(@PathVariable String slug,@AuthenticationPrincipal AuthenticatedUser user){return service.franchiseBySlug(slug,user==null?null:user.id());}
}
