package com.scriptles.cabinet.common.outbox;

public enum DomainEventType {
    MEDIA_LIKED,
    MEDIA_UNLIKED,
    RATING_CREATED,
    RATING_UPDATED,
    RATING_REMOVED,
    MEDIA_COMPLETED,
    MEDIA_UNCOMPLETED,
    LIST_ITEM_ADDED,
    LIST_ITEM_REMOVED,
    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_REMOVED,
    DIARY_ENTRY_CREATED,
    DIARY_ENTRY_UPDATED,
    DIARY_ENTRY_REMOVED,
    MEDIA_IMPORTED,
    MEDIA_METADATA_CHANGED
}
