package com.scriptles.cabinet.catalog.service;
import com.scriptles.cabinet.catalog.api.*; import com.scriptles.cabinet.catalog.collection.CollectionType; import com.scriptles.cabinet.catalog.domain.CatalogEntityStatus; import com.scriptles.cabinet.catalog.entity.*; import com.scriptles.cabinet.catalog.repository.*; import com.scriptles.cabinet.common.api.ApiException; import com.scriptles.cabinet.common.api.PageResponse; import lombok.RequiredArgsConstructor; import org.springframework.cache.annotation.Cacheable; import org.springframework.data.domain.Page; import org.springframework.data.domain.PageRequest; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.List; import java.util.Map; import java.util.UUID;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class CatalogQueryService {
 private final CollectionRepository collections; private final FranchiseRepository franchises; private final CollectionItemRepository items; private final CollectionSectionRepository sections; private final FranchiseCollectionRepository franchiseCollections; private final FranchiseMediaRepository franchiseMedia; private final CollectionArtistRepository collectionArtists;
 public PageResponse<CollectionSummaryResponse> collections(CollectionType type,int page,int size){ Page<Collection> result=collections.findByStatusAndTypeOrderByTitleAscIdAsc(CatalogEntityStatus.ACTIVE,type,PageRequest.of(Math.max(0,page),Math.max(1,Math.min(size,100)))); return PageResponse.from(result.map(c->new CollectionSummaryResponse(c.getId(),c.getSlug(),c.getTitle(),c.getType().name(),null,null))); }
 @Cacheable(cacheNames="collectionDetails",key="#id") public CollectionResponse collection(UUID id,UUID viewerId){ Collection c=collections.findById(id).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); return collectionResponse(c,viewerId); }
 public CollectionResponse collectionBySlug(String slug,UUID viewerId){ Collection c=collections.findBySlug(slug).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); return collection(c.getId(),viewerId); }
 private CollectionResponse collectionResponse(Collection c,UUID viewerId){ List<CollectionItem> its=items.findByCollectionIdOrderByPositionAsc(c.getId()); List<CollectionResponse.SectionResponse> ss=sections.findByCollectionIdOrderByPositionAsc(c.getId()).stream().map(s->new CollectionResponse.SectionResponse(s.getId(),s.getKey(),s.getTitle(),s.getPosition())).toList(); List<CollectionResponse.ItemResponse> ii=its.stream().map(i->new CollectionResponse.ItemResponse(i.getId(),i.getMedia().getId(),i.getMedia().getTitle(),i.getMedia().getTypeValue(),i.getMedia().getCoverUrl(),i.getPosition(),i.getSection()==null?null:i.getSection().getId(),i.getRelationType().name())).toList(); List<FranchiseSummaryResponse> fs=franchiseCollections.findByCollectionId(c.getId()).stream().filter(x->x.getFranchise().getStatus()==CatalogEntityStatus.ACTIVE).map(x->summary(x.getFranchise())).toList(); return new CollectionResponse(c.getId(),c.getSlug(),c.getTitle(),c.getOriginalTitle(),c.getDescription(),c.getType().name(),c.getSourceMode().name(),c.getStatus().name(),c.getPosterUrl(),c.getBackdropUrl(),fs,ss,ii,null); }
 @Cacheable(cacheNames="franchiseDetails",key="#id") public FranchiseResponse franchise(UUID id,UUID viewerId){ Franchise f=franchises.findById(id).orElseThrow(()->notFound("FRANCHISE_NOT_FOUND")); return franchiseResponse(f); }
 public FranchiseResponse franchiseBySlug(String slug,UUID viewerId){ Franchise f=franchises.findBySlug(slug).orElseThrow(()->notFound("FRANCHISE_NOT_FOUND")); return franchise(f.getId(),viewerId); }
 private FranchiseResponse franchiseResponse(Franchise f){ FranchiseSummaryResponse parent=f.getParent()==null?null:summary(f.getParent()); List<FranchiseSummaryResponse> children=franchises.findByParentIdAndStatusOrderByNameAsc(f.getId(),CatalogEntityStatus.ACTIVE).stream().map(this::summary).toList(); List<CollectionSummaryResponse> cs=franchiseCollections.findByFranchiseIdOrderByPositionAsc(f.getId()).stream().filter(x->x.getCollection().getStatus()==CatalogEntityStatus.ACTIVE).map(x->new CollectionSummaryResponse(x.getCollection().getId(),x.getCollection().getSlug(),x.getCollection().getTitle(),x.getCollection().getType().name(),x.getPosition(),(int)items.findByCollectionIdOrderByPositionAsc(x.getCollection().getId()).size())).toList(); List<FranchiseResponse.MediaSummaryResponse> ms=franchiseMedia.findByFranchiseId(f.getId()).stream().map(x->new FranchiseResponse.MediaSummaryResponse(x.getMedia().getId(),x.getMedia().getTitle(),x.getMedia().getTypeValue(),x.getMedia().getCoverUrl())).toList(); return new FranchiseResponse(f.getId(),f.getSlug(),f.getName(),f.getOriginalName(),f.getDescription(),f.getType().name(),f.getStatus().name(),f.getPosterUrl(),f.getBackdropUrl(),parent,children,cs,ms,Map.of()); }
 private FranchiseSummaryResponse summary(Franchise f){return new FranchiseSummaryResponse(f.getId(),f.getSlug(),f.getName(),f.getType().name());}
 private ApiException notFound(String code){return new ApiException(HttpStatus.NOT_FOUND,code,"Entidade de catálogo não encontrada");}
}
