package com.scriptles.cabinet.catalog.service;
import com.scriptles.cabinet.catalog.api.*; import com.scriptles.cabinet.catalog.domain.CatalogEntityStatus; import com.scriptles.cabinet.catalog.entity.*; import com.scriptles.cabinet.catalog.repository.*; import com.scriptles.cabinet.catalog.franchise.FranchiseMediaRelationType; import com.scriptles.cabinet.common.api.*; import com.scriptles.cabinet.media.entity.Media; import com.scriptles.cabinet.media.repository.MediaRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.PageRequest; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.UUID;
@Service @RequiredArgsConstructor @Transactional
public class CatalogModerationService {
 private final CollectionRepository collectionRepository; private final FranchiseRepository franchiseRepository; private final CollectionItemRepository itemRepository; private final FranchiseCollectionRepository franchiseCollectionRepository; private final FranchiseMediaRepository franchiseMediaRepository; private final MediaRepository mediaRepository;
 public Collection saveCollection(UUID id,UpsertCollectionRequest r){ Collection c=id==null?new Collection():collectionRepository.findById(id).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); if(id==null&&collectionRepository.findBySlug(r.slug()).isPresent()) throw conflict(); c.setSlug(r.slug()); c.setTitle(r.title()); c.setOriginalTitle(r.originalTitle()); c.setDescription(r.description()); c.setType(r.type()); c.setSourceMode(r.sourceMode()); c.setStatus(r.status()==null?CatalogEntityStatus.ACTIVE:r.status()); c.setPosterUrl(r.posterUrl()); c.setBackdropUrl(r.backdropUrl()); return collectionRepository.save(c); }
 public Franchise saveFranchise(UUID id,UpsertFranchiseRequest r){ Franchise f=id==null?new Franchise():franchiseRepository.findById(id).orElseThrow(()->notFound("FRANCHISE_NOT_FOUND")); if(id==null&&franchiseRepository.findBySlug(r.slug()).isPresent()) throw conflict(); if(r.parentId()!=null&&(id!=null&&r.parentId().equals(id))) throw new ApiException(HttpStatus.BAD_REQUEST,"FRANCHISE_CYCLE","A franquia não pode ser pai de si mesma"); Franchise parent=r.parentId()==null?null:franchiseRepository.findById(r.parentId()).orElseThrow(()->notFound("PARENT_NOT_FOUND")); if(parent!=null){ Franchise cursor=parent; while(cursor!=null){if(id!=null&&id.equals(cursor.getId())) throw new ApiException(HttpStatus.BAD_REQUEST,"FRANCHISE_CYCLE","A hierarquia contém um ciclo"); cursor=cursor.getParent();}} f.setSlug(r.slug()); f.setName(r.name()); f.setOriginalName(r.originalName()); f.setDescription(r.description()); f.setType(r.type()); f.setStatus(r.status()==null?CatalogEntityStatus.ACTIVE:r.status()); f.setPosterUrl(r.posterUrl()); f.setBackdropUrl(r.backdropUrl()); f.setParent(parent); return franchiseRepository.save(f); }
 private ApiException notFound(String code){return new ApiException(HttpStatus.NOT_FOUND,code,"Entidade não encontrada");} private ApiException conflict(){return new ApiException(HttpStatus.CONFLICT,"SLUG_ALREADY_EXISTS","Slug já existe");}
 public void linkMedia(UUID collectionId, LinkMediaRequest r){ Collection c=collectionRepository.findById(collectionId).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); Media m=mediaRepository.findById(r.mediaId()).orElseThrow(()->notFound("MEDIA_NOT_FOUND")); CollectionItem i=itemRepository.findByCollectionIdAndMediaId(collectionId,r.mediaId()).orElseGet(CollectionItem::new); i.setCollection(c); i.setMedia(m); i.setPosition(r.position()==null?0:r.position()); i.setRelationType(r.relationType()==null?FranchiseMediaRelationType.CORE:r.relationType()); i.setSourceManaged(Boolean.TRUE.equals(r.sourceManaged())); i.setSourceProvider(r.sourceProvider()); itemRepository.save(i); }
 public void linkCollection(UUID franchiseId, LinkCollectionRequest r){ Franchise f=franchiseRepository.findById(franchiseId).orElseThrow(()->notFound("FRANCHISE_NOT_FOUND")); Collection c=collectionRepository.findById(r.collectionId()).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); FranchiseCollection i=franchiseCollectionRepository.findById(new FranchiseCollectionId(franchiseId,r.collectionId())).orElseGet(FranchiseCollection::new); i.setFranchise(f); i.setCollection(c); i.setPosition(r.position()==null?0:r.position()); i.setRelationType(r.relationType()==null?FranchiseMediaRelationType.CORE:r.relationType()); i.setSourceManaged(Boolean.TRUE.equals(r.sourceManaged())); i.setSourceProvider(r.sourceProvider()); franchiseCollectionRepository.save(i); }
 public void hideCollection(UUID id){Collection c=collectionRepository.findById(id).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); c.setStatus(CatalogEntityStatus.HIDDEN);}
 public void hideFranchise(UUID id){Franchise f=franchiseRepository.findById(id).orElseThrow(()->notFound("FRANCHISE_NOT_FOUND")); f.setStatus(CatalogEntityStatus.HIDDEN);}
 public PageResponse<CollectionSummaryResponse> collections(String query,int page,int size){ return PageResponse.from(collectionRepository.findPageByTitleContainingIgnoreCase(query==null?"":query,PageRequest.of(page,size)).map(c->new CollectionSummaryResponse(c.getId(),c.getSlug(),c.getTitle(),c.getType().name(),null,null))); }
 public PageResponse<FranchiseSummaryResponse> franchises(String query,int page,int size){ return PageResponse.from(franchiseRepository.findPageByNameContainingIgnoreCase(query==null?"":query,PageRequest.of(page,size)).map(f->new FranchiseSummaryResponse(f.getId(),f.getSlug(),f.getName(),f.getType().name()))); }
}
