package com.scriptles.cabinet.catalog.service;
import com.scriptles.cabinet.catalog.api.*; import com.scriptles.cabinet.catalog.domain.CatalogEntityStatus; import com.scriptles.cabinet.catalog.entity.*; import com.scriptles.cabinet.catalog.repository.*; import com.scriptles.cabinet.common.api.ApiException; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.UUID;
@Service @RequiredArgsConstructor @Transactional
public class CatalogModerationService {
 private final CollectionRepository collectionRepository; private final FranchiseRepository franchiseRepository;
 public Collection saveCollection(UUID id,UpsertCollectionRequest r){ Collection c=id==null?new Collection():collectionRepository.findById(id).orElseThrow(()->notFound("COLLECTION_NOT_FOUND")); if(id==null&&collectionRepository.findBySlug(r.slug()).isPresent()) throw conflict(); c.setSlug(r.slug()); c.setTitle(r.title()); c.setOriginalTitle(r.originalTitle()); c.setDescription(r.description()); c.setType(r.type()); c.setSourceMode(r.sourceMode()); c.setStatus(r.status()==null?CatalogEntityStatus.ACTIVE:r.status()); c.setPosterUrl(r.posterUrl()); c.setBackdropUrl(r.backdropUrl()); return collectionRepository.save(c); }
 public Franchise saveFranchise(UUID id,UpsertFranchiseRequest r){ Franchise f=id==null?new Franchise():franchiseRepository.findById(id).orElseThrow(()->notFound("FRANCHISE_NOT_FOUND")); if(id==null&&franchiseRepository.findBySlug(r.slug()).isPresent()) throw conflict(); if(r.parentId()!=null&&(id!=null&&r.parentId().equals(id))) throw new ApiException(HttpStatus.BAD_REQUEST,"FRANCHISE_CYCLE","A franquia não pode ser pai de si mesma"); Franchise parent=r.parentId()==null?null:franchiseRepository.findById(r.parentId()).orElseThrow(()->notFound("PARENT_NOT_FOUND")); if(parent!=null){ Franchise cursor=parent; while(cursor!=null){if(id!=null&&id.equals(cursor.getId())) throw new ApiException(HttpStatus.BAD_REQUEST,"FRANCHISE_CYCLE","A hierarquia contém um ciclo"); cursor=cursor.getParent();}} f.setSlug(r.slug()); f.setName(r.name()); f.setOriginalName(r.originalName()); f.setDescription(r.description()); f.setType(r.type()); f.setStatus(r.status()==null?CatalogEntityStatus.ACTIVE:r.status()); f.setPosterUrl(r.posterUrl()); f.setBackdropUrl(r.backdropUrl()); f.setParent(parent); return franchiseRepository.save(f); }
 private ApiException notFound(String code){return new ApiException(HttpStatus.NOT_FOUND,code,"Entidade não encontrada");} private ApiException conflict(){return new ApiException(HttpStatus.CONFLICT,"SLUG_ALREADY_EXISTS","Slug já existe");}
}
