create table profiles (
 id uuid primary key default gen_random_uuid(), type varchar(20) not null, user_id uuid unique references users(id) on delete cascade,
 handle varchar(80) not null unique, display_name varchar(120) not null, avatar_url varchar(500), backdrop_url varchar(500), bio text,
 verified boolean not null default false, verified_at timestamptz, followers_count bigint not null default 0, following_count bigint not null default 0,
 active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index idx_profiles_user on profiles(user_id);
insert into profiles(type,user_id,handle,display_name,avatar_url,bio,created_at,updated_at)
select 'MEMBER', id, username, display_name, avatar_ulr, biography, coalesce(created_at,now()), coalesce(updated_at,now()) from users
where not exists (select 1 from profiles p where p.user_id=users.id);
create table hq_profiles (id uuid primary key default gen_random_uuid(), profile_id uuid not null unique references profiles(id) on delete cascade, hq_type varchar(40) not null, legal_name varchar(160), website_url varchar(500), contact_email varchar(254), country_code varchar(2), founded_year integer, claim_status varchar(30) not null default 'UNCLAIMED', external_source varchar(30), external_id varchar(255), last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table catalog_organizations (id uuid primary key default gen_random_uuid(), type varchar(40) not null, canonical_name varchar(200) not null, aliases text, country_code varchar(2), website_url varchar(500), logo_url varchar(500), description text, primary_source varchar(30) not null, primary_external_id varchar(255) not null, last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(primary_source,primary_external_id));
create table organization_external_references (id uuid primary key default gen_random_uuid(), organization_id uuid not null references catalog_organizations(id) on delete cascade, source varchar(30) not null, external_id varchar(255) not null, external_url varchar(500), unique(source,external_id));
create table hq_catalog_links (id uuid primary key default gen_random_uuid(), hq_profile_id uuid not null references hq_profiles(id) on delete cascade, organization_id uuid not null references catalog_organizations(id) on delete cascade, unique(hq_profile_id,organization_id));
create table hq_members (id uuid primary key default gen_random_uuid(), hq_profile_id uuid not null references hq_profiles(id) on delete cascade, account_id uuid not null references users(id) on delete cascade, role varchar(20) not null, created_at timestamptz not null default now(), unique(hq_profile_id,account_id));
create table hq_claims (id uuid primary key default gen_random_uuid(), hq_profile_id uuid not null references hq_profiles(id) on delete cascade, requested_by_account_id uuid not null references users(id), organization_email varchar(254) not null, evidence_url varchar(500), message text, status varchar(30) not null default 'PENDING', reviewed_by_account_id uuid references users(id), reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index idx_hq_claims_status on hq_claims(status,created_at);
create table profile_posts (id uuid primary key default gen_random_uuid(), author_profile_id uuid not null references profiles(id) on delete cascade, type varchar(20) not null, status varchar(20) not null default 'DRAFT', title varchar(200), body text, link_url varchar(500), published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index idx_profile_posts_public on profile_posts(author_profile_id,status,published_at);
create table profile_follows (id uuid primary key default gen_random_uuid(), follower_profile_id uuid not null references profiles(id) on delete cascade, followed_profile_id uuid not null references profiles(id) on delete cascade, status varchar(20) not null default 'ACCEPTED', created_at timestamptz not null default now(), unique(follower_profile_id,followed_profile_id), check(follower_profile_id<>followed_profile_id), check(status in ('PENDING','ACCEPTED')));
create index idx_profile_follows_followed on profile_follows(followed_profile_id,created_at desc);
create table media_organizations (id uuid primary key default gen_random_uuid(), media_id uuid not null references media(id) on delete cascade, organization_id uuid not null references catalog_organizations(id) on delete cascade, relationship varchar(30) not null, unique(media_id,organization_id,relationship));
create index idx_media_organizations_org on media_organizations(organization_id,media_id);
