package com.scriptles.cabinet.profile.service;

import com.scriptles.cabinet.common.api.ApiException; import com.scriptles.cabinet.common.api.PageResponse; import com.scriptles.cabinet.profile.dto.*; import com.scriptles.cabinet.profile.entity.*; import com.scriptles.cabinet.profile.enums.*; import com.scriptles.cabinet.profile.repository.*; import com.scriptles.cabinet.user.entity.User; import com.scriptles.cabinet.user.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.PageRequest; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;

@Service @RequiredArgsConstructor
public class ProfileService {
 private final ProfileRepository profiles; private final HQProfileRepository hqs; private final HQCatalogLinkRepository links; private final HQMemberRepository members; private final ProfileFollowRepository follows; private final UserRepository users; private final CatalogOrganizationRepository organizations; private final MediaOrganizationRepository mediaOrganizations;
 @Transactional(readOnly=true)
 public ProfileResponse find(String handle, UUID viewerId) {
  Profile p=profiles.findByHandleIgnoreCase(handle.trim()).filter(Profile::isActive).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado"));
  HQProfile hq=hqs.findByProfileId(p.getId()).orElse(null); boolean following=viewerId!=null&&profiles.findByUserId(viewerId).map(member->follows.existsByFollowerIdAndFollowedId(member.getId(),p.getId())).orElse(false);
  boolean manage=viewerId!=null&&hq!=null&&members.findByHqProfileIdAndAccountId(hq.getId(),viewerId).map(m->m.getRole()==HQMemberRole.OWNER||m.getRole()==HQMemberRole.ADMIN||m.getRole()==HQMemberRole.EDITOR).orElse(false);
  ProfileResponse.HQDetails details=hq==null?null:new ProfileResponse.HQDetails(hq.getId(),hq.getHqType(),hq.getWebsiteUrl(),hq.getCountryCode(),hq.getClaimStatus());
  List<String> nav=hq==null?List.of("LIBRARY","ACTIVITY","LISTS"):List.of("CATALOG","LISTS","POSTS","ABOUT");
  List<String> sections=hq==null?List.of():links.findByHqProfileId(hq.getId()).stream().map(l->l.getOrganization().getType().name()).distinct().toList();
  return new ProfileResponse(p.getId(),p.getType(),p.getHandle(),p.getDisplayName(),p.getAvatarUrl(),p.getBackdropUrl(),p.getBio(),p.isVerified(),p.getFollowersCount(),p.getFollowingCount(),details,nav,sections,new ProfileResponse.Viewer(following,manage,hq!=null&&hq.getClaimStatus()==HQClaimStatus.UNCLAIMED));
 }
 @Transactional(readOnly=true) public PageResponse<ProfileSearchResponse> search(String q,int page,int size){ var result=profiles.search(q.trim(),PageRequest.of(page,size)); return PageResponse.from(result.map(p->new ProfileSearchResponse(p.getId(),p.getType(),p.getHandle(),p.getDisplayName(),p.getAvatarUrl(),p.isVerified(),null))); }
 @Transactional(readOnly=true) public PageResponse<CatalogItemResponse> catalog(String handle,int page,int size){ HQProfile h=hqs.findByProfileHandleIgnoreCase(handle).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado")); return PageResponse.from(mediaOrganizations.findMediaForHq(h.getId(),PageRequest.of(page,size)).map(m->new CatalogItemResponse(m.getId(),m.getType(),m.getTitle(),m.getCoverUrl(),m.getReleaseDate()))); }
 @Transactional public void follow(UUID accountId,UUID targetId){ Profile follower=memberProfile(accountId); Profile target=profiles.findById(targetId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado")); if(follower.getId().equals(target.getId())) throw error("INVALID_FOLLOW","Não é possível seguir a si mesmo"); if(!follows.existsByFollowerIdAndFollowedId(follower.getId(),target.getId())){ ProfileFollow f=new ProfileFollow();f.setFollower(follower);f.setFollowed(target);follows.save(f); follower.setFollowingCount(follower.getFollowingCount()+1); target.setFollowersCount(target.getFollowersCount()+1); } }
 @Transactional public void unfollow(UUID accountId,UUID targetId){ Profile follower=memberProfile(accountId); if(follows.existsByFollowerIdAndFollowedId(follower.getId(),targetId)){ follows.deleteByFollowerIdAndFollowedId(follower.getId(),targetId); follower.setFollowingCount(Math.max(0,follower.getFollowingCount()-1)); profiles.findById(targetId).ifPresent(p->p.setFollowersCount(Math.max(0,p.getFollowersCount()-1))); } }
 @Transactional public Profile createHQ(CatalogOrganization org,HQType type,String handle){ if(profiles.existsByHandleIgnoreCase(handle)) throw error("HANDLE_TAKEN","Handle já está em uso"); Profile p=new Profile();p.setType(ProfileType.HQ);p.setHandle(handle);p.setDisplayName(org.getCanonicalName());p.setAvatarUrl(org.getLogoUrl());p.setBio(org.getDescription());p=profiles.save(p); HQProfile h=new HQProfile();h.setProfile(p);h.setHqType(type);h.setCountryCode(org.getCountryCode());h.setWebsiteUrl(org.getWebsiteUrl());h.setExternalSource(org.getPrimarySource());h.setExternalId(org.getPrimaryExternalId());hqs.save(h); HQCatalogLink l=new HQCatalogLink();l.setHqProfile(h);l.setOrganization(org);links.save(l); return p; }
 @Transactional public Profile createOfficialHQ(CatalogOrganization org,HQType type,String handle, User owner){ Profile p=createHQ(org,type,handle); HQProfile h=hqs.findByProfileId(p.getId()).orElseThrow(); h.setClaimStatus(HQClaimStatus.CLAIMED); p.setVerified(true); p.setVerifiedAt(java.time.Instant.now()); HQMember m=new HQMember();m.setHqProfile(h);m.setAccount(owner);m.setRole(HQMemberRole.OWNER);members.save(m); return p; }
 @Transactional(readOnly=true) public Optional<Profile> existingHQ(String source,String externalId){ return hqs.findByExternalSourceAndExternalId(source,externalId).map(HQProfile::getProfile); }
 Profile memberProfile(UUID id){ return profiles.findByUserId(id).orElseGet(()->{ User u=users.findById(id).orElseThrow(); return profiles.save(Profile.member(u)); }); }
 static ApiException error(String code,String message){return new ApiException(HttpStatus.NOT_FOUND,code,message);}
}
