package com.scriptles.cabinet.profile.service;

import com.scriptles.cabinet.common.api.ApiException; import com.scriptles.cabinet.common.api.PageResponse; import com.scriptles.cabinet.common.api.RichTextDocument; import com.scriptles.cabinet.profile.dto.*; import com.scriptles.cabinet.profile.entity.*; import com.scriptles.cabinet.profile.enums.*; import com.scriptles.cabinet.profile.repository.*; import com.scriptles.cabinet.user.entity.User; import com.scriptles.cabinet.user.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.PageRequest; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;

@Service @RequiredArgsConstructor
public class ProfileService {
 private final ProfileRepository profiles; private final HQProfileRepository hqs; private final HQCatalogLinkRepository links; private final ProfileFollowRepository follows; private final UserRepository users; private final CatalogOrganizationRepository organizations; private final MediaOrganizationRepository mediaOrganizations;
 @Transactional(readOnly=true)
 public ProfileResponse find(String handle, UUID viewerId) {
  Profile p=profiles.findByHandleIgnoreCase(handle.trim()).filter(Profile::isActive).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado"));
  HQProfile hq=hqs.findByProfileId(p.getId()).orElse(null); boolean following=viewerId!=null&&profiles.findByUserId(viewerId).map(member->follows.existsByFollowerIdAndFollowedId(member.getId(),p.getId())).orElse(false);
  boolean manage=false;
  ProfileResponse.HQDetails details=hq==null?null:new ProfileResponse.HQDetails(hq.getId(),hq.getHqType(),hq.getWebsiteUrl(),hq.getCountryCode(),hq.getClaimStatus());
  List<String> nav=hq==null?List.of("LIBRARY","ACTIVITY","LISTS"):List.of("CATALOG","LISTS","REVIEWS","POSTS","ABOUT");
  List<String> sections=hq==null?List.of():links.findByHqProfileId(hq.getId()).stream().map(l->l.getOrganization().getType().name()).distinct().toList();
  return new ProfileResponse(p.getId(),p.getType(),p.getHandle(),p.getDisplayName(),p.getAvatarUrl(),p.getBackdropUrl(),p.getBio(),p.isVerified(),p.getFollowersCount(),p.getFollowingCount(),details,nav,sections,new ProfileResponse.Viewer(following,manage,viewerId!=null&&hq!=null&&hq.getClaimStatus()==HQClaimStatus.UNCLAIMED),p.getRichBio()==null?null:RichTextDocument.parse(p.getRichBio()));
 }
 @Transactional(readOnly=true) public PageResponse<ProfileSearchResponse> search(String q,int page,int size,ProfileType type){ var pageable=PageRequest.of(page,size); var result=type==null?profiles.search(q.trim(),pageable):profiles.searchByType(q.trim(),type,pageable); return PageResponse.from(result.map(p->new ProfileSearchResponse(p.getId(),p.getType(),p.getHandle(),p.getDisplayName(),p.getAvatarUrl(),p.isVerified(),null))); }
 @Transactional(readOnly=true) public PageResponse<CatalogItemResponse> catalog(String handle,int page,int size){ HQProfile h=hqs.findByProfileHandleIgnoreCase(handle).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado")); return PageResponse.from(mediaOrganizations.findMediaForHq(h.getId(),PageRequest.of(page,size)).map(m->new CatalogItemResponse(m.getId(),m.getType(),m.getTitle(),m.getCoverUrl(),m.getReleaseDate()))); }
 @Transactional public void follow(UUID accountId,UUID targetId){ Profile follower=memberProfile(accountId); Profile target=profiles.findById(targetId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado")); if(follower.getId().equals(target.getId())) throw error("INVALID_FOLLOW","Não é possível seguir a si mesmo"); if(!follows.existsByFollowerIdAndFollowedId(follower.getId(),target.getId())){ ProfileFollow f=new ProfileFollow();f.setFollower(follower);f.setFollowed(target);follows.save(f); follower.setFollowingCount(follower.getFollowingCount()+1); target.setFollowersCount(target.getFollowersCount()+1); } }
 @Transactional public void unfollow(UUID accountId,UUID targetId){ Profile follower=memberProfile(accountId); if(follows.existsByFollowerIdAndFollowedId(follower.getId(),targetId)){ follows.deleteByFollowerIdAndFollowedId(follower.getId(),targetId); follower.setFollowingCount(Math.max(0,follower.getFollowingCount()-1)); profiles.findById(targetId).ifPresent(p->p.setFollowersCount(Math.max(0,p.getFollowersCount()-1))); } }
 @Transactional public Profile createHQ(CatalogOrganization org,HQType type,String handle){ if(profiles.existsByHandleIgnoreCase(handle)) throw error("HANDLE_TAKEN","Handle já está em uso"); Profile p=new Profile();p.setType(ProfileType.HQ);p.setHandle(handle);p.setDisplayName(org.getCanonicalName());p.setAvatarUrl(org.getLogoUrl());p.setBio(org.getDescription());p=profiles.save(p); HQProfile h=new HQProfile();h.setProfile(p);h.setHqType(type);h.setCountryCode(org.getCountryCode());h.setWebsiteUrl(org.getWebsiteUrl());h.setExternalSource(org.getPrimarySource());h.setExternalId(org.getPrimaryExternalId());hqs.save(h); HQCatalogLink l=new HQCatalogLink();l.setHqProfile(h);l.setOrganization(org);links.save(l); return p; }
 @Transactional public Profile createOfficialHQ(CatalogOrganization org,HQType type,String handle){ Profile p=createHQ(org,type,handle); HQProfile h=hqs.findByProfileId(p.getId()).orElseThrow(); h.setClaimStatus(HQClaimStatus.CLAIMED); p.setVerified(true); p.setVerifiedAt(java.time.Instant.now()); return p; }
 @Transactional(readOnly=true) public Optional<Profile> existingHQ(String source,String externalId){ return hqs.findByExternalSourceAndExternalId(source,externalId).map(HQProfile::getProfile); }
 @Transactional(readOnly=true) public ProfileResponse findById(UUID profileId){ Profile p=profiles.findById(profileId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil não encontrado")); return find(p.getHandle(),null); }
 @Transactional(readOnly=true) public PageResponse<HQAdminSummaryResponse> adminHQs(String query,int page,int size){ return PageResponse.from(hqs.search(query==null?"":query.trim(),PageRequest.of(page,size)).map(h->new HQAdminSummaryResponse(h.getProfile().getId(),h.getProfile().getHandle(),h.getProfile().getDisplayName(),h.getProfile().getAvatarUrl(),h.getHqType(),h.getClaimStatus(),h.getProfile().isVerified(),h.getProfile().getFollowersCount()))); }
 @Transactional public ProfileResponse updateHQ(UUID profileId,HQUpdateRequest request,UUID viewerId){ HQProfile h=hqs.findByProfileId(profileId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil HQ não encontrado")); if(!users.findById(viewerId).map(u->u.getRole()!=null&&u.getRole().name().equals("ADMIN")).orElse(false)) throw new ApiException(HttpStatus.FORBIDDEN,"HQ_FORBIDDEN","Use o painel da HQ"); return updateHQByOperator(profileId,request); }
 @Transactional public ProfileResponse updateHQByOperator(UUID profileId,HQUpdateRequest request){ HQProfile h=hqs.findByProfileId(profileId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil HQ não encontrado")); if(h.getClaimStatus()==HQClaimStatus.SUSPENDED) throw new ApiException(HttpStatus.FORBIDDEN,"HQ_SUSPENDED","HQ suspensa"); Profile p=h.getProfile(); if(request.displayName()!=null)p.setDisplayName(request.displayName().trim()); if(request.bio()!=null)p.setBio(request.bio()); if(request.richBio()!=null){ String text=RichTextDocument.validateAndExtractText(request.richBio(),true); if(text.length()>5000) throw new ApiException(HttpStatus.BAD_REQUEST,"BIO_TOO_LONG","A bio deve ter no máximo 5000 caracteres"); if(request.bio()!=null&&!text.equals(request.bio())) throw new ApiException(HttpStatus.BAD_REQUEST,"RICH_TEXT_MISMATCH","A bio deve corresponder ao documento formatado"); p.setBio(text); p.setRichBio(request.richBio()); } else if(request.bio()!=null) p.setRichBio(null); if(request.avatarUrl()!=null)p.setAvatarUrl(request.avatarUrl()); if(request.backdropUrl()!=null)p.setBackdropUrl(request.backdropUrl()); if(request.websiteUrl()!=null)h.setWebsiteUrl(request.websiteUrl()); if(request.contactEmail()!=null)h.setContactEmail(request.contactEmail().trim().toLowerCase(Locale.ROOT)); if(request.legalName()!=null)h.setLegalName(request.legalName()); if(request.countryCode()!=null)h.setCountryCode(request.countryCode().toUpperCase(Locale.ROOT)); return find(p.getHandle(),null); }
 @Transactional public ProfileResponse updateHQBackdrop(UUID profileId,String backdropUrl,UUID viewerId){ HQProfile h=hqs.findByProfileId(profileId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil HQ não encontrado")); authorizeHQEditor(h,viewerId); h.getProfile().setBackdropUrl(backdropUrl); return find(h.getProfile().getHandle(),viewerId); }
 private void authorizeHQEditor(HQProfile h,UUID viewerId){ if(h.getClaimStatus()==HQClaimStatus.SUSPENDED) throw new ApiException(HttpStatus.FORBIDDEN,"HQ_SUSPENDED","HQ suspensa"); boolean admin=users.findById(viewerId).map(u->u.getRole()!=null&&u.getRole().name().equals("ADMIN")).orElse(false); if(!admin) throw new ApiException(HttpStatus.FORBIDDEN,"HQ_FORBIDDEN","Use o painel da HQ"); }
 @Transactional(readOnly=true) public void ensureCanManageHQ(UUID profileId,UUID viewerId){ HQProfile h=hqs.findByProfileId(profileId).orElseThrow(()->error("PROFILE_NOT_FOUND","Perfil HQ não encontrado")); authorizeHQEditor(h,viewerId); }
 Profile memberProfile(UUID id){ return profiles.findByUserId(id).orElseGet(()->{ User u=users.findById(id).orElseThrow(); return profiles.save(Profile.member(u)); }); }
 static ApiException error(String code,String message){return new ApiException(HttpStatus.NOT_FOUND,code,message);}
}
